### ISSUE TITLE
Parser::disableCache was removed in MediaWiki 1.35 causing error

### ISSUE THREAD

**Issue by andrecastro0o** [Wikimedica/mediawiki-extensions-GetUserName#4]
As mentioned in [PDFEmbed/-/issues/19](https://gitlab.com/hydrawiki/extensions/PDFEmbed/-/issues/19) `Parser::disableCache` has been deprecated in Mediawiki 1.28 and was removed in MediaWiki 1.35. 
Its presence in GetUserName source causes GetUserName to be incompatible with Mediawiki 1.35.

The issue has been resolved on my side by commenting that line:
https://github.com/Wikimedica/mediawiki-extensions-GetUserName/blob/97a88deb8645d576989251c3535e721176001622/GetUserName.class.php#L32

[PDFEmbed/-/issues/19](https://gitlab.com/hydrawiki/extensions/PDFEmbed/-/issues/19)  suggests 
> replacing the disableCache call in PDFEmbed.hooks.php with:
$parser->getOutput()->updateCacheExpiry( 60 );

**Comment by bitsofmymind** [comment]
Thanks for the bug report!

You cannot simply comment out that line (unless caching is disabled as a whole in your wiki) because the page needs to be rerendered for every different user.

I've fixed this in master, REL1_34 and REL1_35.

**Comment by andrecastro0o** [comment]
:+1:  thanks. Also for adding the REL1_35 branch
